// Code generated by mockery v2.43.2. DO NOT EDIT.

package mockgithub

import (
	github "github.com/renegumroad/gum-cli/internal/github"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Projects provides a mock function with given fields:
func (_m *MockClient) Projects() github.Projects {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Projects")
	}

	var r0 github.Projects
	if rf, ok := ret.Get(0).(func() github.Projects); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(github.Projects)
		}
	}

	return r0
}

// MockClient_Projects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Projects'
type MockClient_Projects_Call struct {
	*mock.Call
}

// Projects is a helper method to define mock.On call
func (_e *MockClient_Expecter) Projects() *MockClient_Projects_Call {
	return &MockClient_Projects_Call{Call: _e.mock.On("Projects")}
}

func (_c *MockClient_Projects_Call) Run(run func()) *MockClient_Projects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Projects_Call) Return(_a0 github.Projects) *MockClient_Projects_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Projects_Call) RunAndReturn(run func() github.Projects) *MockClient_Projects_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
