version: '3'

env:
  PKGS:
    sh: go list ./... | grep -v "/vendor/\|/example"
  VERSION:
    sh: git rev-parse HEAD
  COMMIT:
    sh: git rev-parse HEAD
  BRANCH:
    sh: git rev-parse --abbrev-ref HEAD

tasks:
  build:
    cmds:
      - |
        go build -v -o build/darwin_arm64/gum \
          -ldflags "-s -w \
          -X github.com/renegumroad/gum-cli/internal/version.VERSION=${VERSION}" \
          main.go

  test:
    cmds:
      - go test -v $PKGS -race

  fmt:
    cmds:
      - go fmt $PKGS

  vet:
    cmds:
      - go vet -copylocks=false $PKGS

  lint:
    cmds:
      - golangci-lint run

  release-check:
    cmds:
      - goreleaser check

  release-build:
    cmds:
      - goreleaser build --snapshot --clean
