// Code generated by mockery v2.43.2. DO NOT EDIT.

package mockprojectconfig

import mock "github.com/stretchr/testify/mock"

// MockProjectConfig is an autogenerated mock type for the ProjectConfig type
type MockProjectConfig struct {
	mock.Mock
}

type MockProjectConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectConfig) EXPECT() *MockProjectConfig_Expecter {
	return &MockProjectConfig_Expecter{mock: &_m.Mock}
}

// LatestVersion provides a mock function with given fields:
func (_m *MockProjectConfig) LatestVersion() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LatestVersion")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectConfig_LatestVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestVersion'
type MockProjectConfig_LatestVersion_Call struct {
	*mock.Call
}

// LatestVersion is a helper method to define mock.On call
func (_e *MockProjectConfig_Expecter) LatestVersion() *MockProjectConfig_LatestVersion_Call {
	return &MockProjectConfig_LatestVersion_Call{Call: _e.mock.On("LatestVersion")}
}

func (_c *MockProjectConfig_LatestVersion_Call) Run(run func()) *MockProjectConfig_LatestVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProjectConfig_LatestVersion_Call) Return(_a0 string, _a1 error) *MockProjectConfig_LatestVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectConfig_LatestVersion_Call) RunAndReturn(run func() (string, error)) *MockProjectConfig_LatestVersion_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectConfig creates a new instance of MockProjectConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectConfig {
	mock := &MockProjectConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
